### ISSUE TITLE
pages配下のコンポーネント命名に関して

### ISSUE THREAD

**Issue by tatsuya19881021** [kyoichi1/portfolio-1-e-k#88]
src/pages 配下のコンポーネントが、
（例えば、src/pages/blog.tsxなど）
blog などと小文字始まりになっているので、
Blog などのパスカルケースで付けてあげたほうが良いと思います。
（そのような流儀があった気がしますが、嘘ついてたらすみません）

それで、src/component 配下のコンポーネントと被ってしまうと言う話は、
どちらかの名称を変えちゃったら良いかなー。と思います。

- src/component のほうは、BlogContainerとかそれっぽい名称にする
または
- src/pages のほうを、BlogPagesとかにするなどやり方は色々ありそうです。
（どちらか片方だけ対応すれば問題ないです😀）

**Comment by kyoichi1** [comment]
@tatsuya19881021 

ありがとうございます🙏✨
pagesの方はパスカルケースにて変更させて頂きました🙏✨
pagesは〇〇Pages.に変更してcomponetのと名前が被っていたところを修正致しました。

**Comment by tatsuya19881021** [comment]
対応お疲れ様です。

惜しいやつが混ざっているので、以下に記載します。
ここまでは修正された方が、より良いと思いました🙇

- `src/pages/index.tsx`のコンポーネント名が全て大文字になっている。
- `src/component/Blog/BlogDetails.tsx`のタイプ名が小文字始まりになっている。

**Comment by kyoichi1** [comment]
ありがとうございます🙏✨
②は修正できたのですが、すみません①のところが理解ができてなくて....🥺
コンポーネント名については大文字だめだったのでしょうか...😱

🙅‍♂️①src/pages/index.tsxのコンポーネント名が全て大文字になっている。
🙆②src/component/Blog/BlogDetails.tsxのタイプ名が小文字始まりになっている。

**Comment by tatsuya19881021** [comment]
> ありがとうございます🙏✨ ②は修正できたのですが、すみません①のところが理解ができてなくて....🥺 コンポーネント名については大文字だめだったのでしょうか...😱
> 
> 🙅‍♂️①src/pages/index.tsxのコンポーネント名が全て大文字になっている。 🙆②src/component/Blog/BlogDetails.tsxのタイプ名が小文字始まりになっている。

→ ①これは、どうなんですかね〜。HOMEとされていますが…
他のコンポーネントの統一感としても、パスカルケースの方が収まりが良いと思いました。
全て大文字なのがダメかは、ちょっと勉強不足です🙏
