### ISSUE TITLE
main以外のブランチについて

### ISSUE THREAD

**Issue by tatsuya19881021** [kyoichi1/portfolio-1-e-k#90]
### main以外のブランチ

- 72-microcmsでお問い合わせページの作成
- 82-リファクタリング
- 86-リファクタリングprettier設定

上記のブランチそれぞれの履歴を見てみましたが、
mainにも同じcommitが存在するので消しても良さそうだと思います。

一応、ブランチの削除となると自己責任でやってもらうべきだと思うので、
あくまでこちらからは提案と言う形になります。

とは言え、いつまでも残っていると、ずっと混乱のもとになりそうなので、
消すのがオススメなんじゃないかな〜？と考えます。

_最後に、特にVSCode（ローカル）上で、ローカルブランチを削除していないのであれば、
GitHub上のブランチを消しても、ローカルに残るようです。
どうしても必要になった場合には、ローカルから改めてプッシュすることが出来ると思います。_

**Comment by kyoichi1** [comment]
@tatsuya19881021 

下記３ブランチ無事削除成功致しました。

72-microcmsでお問い合わせページの作成
82-リファクタリング
86-リファクタリングprettier設定

めちゃくちゃスッキリしました☺️✨
次回から気をつけて作成していきます🙇
