### ISSUE TITLE
exportについて

### ISSUE THREAD

**Issue by tatsuya19881021** [kyoichi1/portfolio-1-e-k#92]
追加ですみません。

pages配下はdefaultエクスポートで良い（そうでないといけない）ですが、
component配下はdefaultでないエクスポートが良いそうですよ〜。
（defaultは、インポート時に名称変えられるとか問題があるから推奨しないって話だったかと）

すぐに修正しなくても良いですが、いつか対応されると良いかもです😀

**Comment by kyoichi1** [comment]
ありがとうございます🙏✨
あっ...しまぶーさんの動画でも聞いた気がします...😱
Qiitaの記事でも今調べたらエラーに気づきにくくて後々大変になるとのことだそうです😱
大至急named exportに変更します🙇

**Comment by kyoichi1** [comment]
すみません....コンポーネントで使うnamed exportとは

About >index.tsx だったら

9行目　`const About = (props: AboutProps) => {`　→    `export const About = (props: AboutProps) => {`　に変更して

２８行目　`export default About;`　を削除する感じで良いのでしょうか🥺？？

**Comment by tatsuya19881021** [comment]
ですです。

ご認識の通りに対応してもらえれば、問題ありません。

default export の場合には、const と分けないといけないですが、今回は上記の内容で間違いありません👍

**Comment by kyoichi1** [comment]
ありがとうございます🙏✨✨
